application:
  port: 8080
  host: "0.0.0.0"
  domain: "localhost"
  bodylimit: "25mib"
  ipv6: false

database:
  user: "postgres"
  password: "123"       # ← Change from "password" to "123"
  host: "db-pemasak"    # ← Change from "localhost" to "db-pemasak" 
  port: 5432
  name: "postgres"      # ← Change from "dev" to "postgres"
  timeout: 20

git:
  auth: true
  base: "./git-repo"

log:
  dev: false

auth:
  sso: false
  # in hour
  lifespan: 168
  cookiename: session
  # in days
  maxage: 365
  httponly: true
  secure: false
  # in days
  maxlifespan: 365

build:
  max: 2
  # in microseconds (100ms === 1 CPU allocation)
  cpums: 100000
  # in miliseconds
  timeout: 120000

container:
  cpu: 0.5
  # amount of swap = memory_swap - memory_limit
  memory: 256M
  swap: 320M

grafana:
  user: "user"
  password: "password"
