server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Filter cuma container server-pemasak
      - source_labels: ['__meta_docker_container_name']
        regex: 'server-pemasak'  # HAPUS / di depan!
        action: keep
      
      # Set label container_name
      - source_labels: ['__meta_docker_container_name'] 
        target_label: 'container_name'
        
      # Set stream label
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
        
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: fields.message
            method: span.method
            uri: span.uri
            status: fields.status
            latency: fields.latency
      - labels:
          level:
          method:
          status: